name: 'helm-gh-pages'
description: 'A GitHub Action to publish helm charts to Github Pages'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  token:
    description: "GitHub token"
    required: true
  charts_dir:
    description: "The charts directory, defaults to `charts`"
    required: false
  charts_url:
    description: "The GitHub Pages URL, default to `https://<USER>.github.io/<REPOSITORY>`"
    required: false
  user:
    description: "The GitHub user that owns this repository"
    required: false
  repository:
    description: "The GitHub repository name"
    required: false
  branch:
    description: "The branch to publish charts, default to `gh-pages`"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.charts_dir }}
    - ${{ inputs.charts_url }}
    - ${{ inputs.user }}
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}