---
kind: pipeline
name: linux-arm-docker

platform:
  os: linux
  arch: arm

  - name: dryrun
    pull: always
    image: plugins/docker:linux-arm
    settings:
      dockerfile: Dockerfile.arm
      dry_run: true
      repo: stefanprodan/podinfo-arm
      tags: linux-arm
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        - push
        - pull_request