---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: plugins/docker:linux-arm
  settings:
    dry_run: true
    dockerfile: Dockerfile.arm
    repo: stefanprodan/podinfo-arm
    tag: linux-arm
  when:
    event:
    - push
    - pull_request

- name: push
  image: plugins/docker:linux-arm
  settings:
    dockerfile: Dockerfile.arm
    repo: stefanprodan/podinfo-arm
    tag: "${DRONE_COMMIT_SHA:0:8}"
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
  when:
    branch:
    - master