sudo: required
language: go

go:
  - 1.11.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - make dep
  - go get sigs.k8s.io/kind
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - kind create cluster
  - export KUBECONFIG="$(kind get kubeconfig-path --name="1")"
  - ./kubectl cluster-info

script:
  - make test
  - make build docker-build

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    else
      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin;
      make docker-push;
    fi
  - if [ -z "$QUAY_USER" ]; then
      echo "PR build, skipping Quay push";
    else
      echo $QUAY_PASS | docker login -u $QUAY_USER --password-stdin quay.io;
      make quay-push;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
