sudo: required
language: go

go:
  - 1.9.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - make dep
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
  - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
  - wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.8.sh && chmod +x dind-cluster-v1.8.sh && ./dind-cluster-v1.8.sh up
  - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"

script:
  - kubectl get nodes
  - docker ps
  - make test
  - make build docker-build
  - docker save stefanprodan/podinfo:latest | docker exec -i kube-node-1 docker load

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    else
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      make docker-push;
    fi
