sudo: required
language: go

go:
  - 1.12.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - make build-container

after_success:
  - if [ -z "$TRAVIS_TAG" ]; then
      echo "Not a release, skipping container push";
    else
      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin;
      echo $QUAY_PASS | docker login -u $QUAY_USER --password-stdin quay.io;
      make push-container;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
