sudo: required
language: go

go:
  - 1.9.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - make dep
  - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update -qq && apt-get install -qy kubeadm
  - kubeadm init

script:
  - make test
  - make build docker-build

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    else
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      make docker-push;
    fi
