---
apiVersion: v1
kind: Service
metadata:
  name: green
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: green
      prefix: /
      host: green.test
      service: green.default:9898
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
  selector:
    app: green
