---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-clusterip
  labels:
    app: podinfo
spec:
  type: ClusterIP
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
  selector:
    app: podinfo
