#---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: podinfo-gateway
#spec:
#  selector:
#    app: podinfo
#  servers:
#  - port:
#      number: 9898
#      name: http
#    hosts:
#    - podinfo.test
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: podinfo
#spec:
#  hosts:
#  - podinfo
#  http:
#  - match:
#    - headers:
#        x-user:
#          exact: insider
#    route:
#    - destination:
#        name: podinfo-canary
#        subset: canary
#  - route:
#    - destination:
#        name: podinfo-ga
#        subset: ga
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: podinfo-ga
#spec:
#  name: podinfo-ga
#  subsets:
#  - name: ga
#    labels:
#      release: ga
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: podinfo-canary
#spec:
#  name: podinfo-canary
#  subsets:
#  - name: canary
#    labels:
#      release: canary
