name: lint

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: helm
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            helmv3 template ./charts/podinfo | kubeval --strict
      - name: kubeval
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            kustomize build ./kustomize | kubeval --strict
      - name: conftest
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            kustomize build ./kustomize | conftest test -p .github/policy -
